In [1]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.6     ✔ dplyr   1.0.8
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [4]:
small_raw <- read.csv("../rentalbond-data-tla.csv")
head(small_raw)

  Time.Frame Location.Id Location                   Lodged.Bonds Active.Bonds
1 1993-02-01 -99         ALL                        9,147        95,583
2 1993-02-01  -1         NA                         528          6,285
3 1993-02-01   1         Far North District         45           468
4 1993-02-01   2         Whangarei District         120          1,248
5 1993-02-01   3         Kaipara District           12           108
6 1993-02-01  11         Thames-Coromandel District 39           324
  Closed.Bonds Median.Rent Geometric.Mean.Rent Upper.Quartile.Rent
1 7155         150         151                 200
2  435         130         128                 165
3   24         120         112                 136
4  108         120         121                 150
5   12         118         113                 121
6   21         120         121                 146
  Lower.Quartile.Rent Log.Std.Dev.Weekly.Rent
1 120                 0.43
2 100                 0.47
3  95                 0.30
4 100                 0.30
5  98                 0.31
6 100                 0.29

In [6]:
large_raw <- read_csv("../Detailed Quarterly Tenancy.csv")
head(large_raw)

Warning message:
“One or more parsing issues, see `problems()` for details”
Rows: 1007918 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): Time Frame, Dwelling Type, Number Of Beds
dbl (4): Median Rent, Upper Quartile Rent, Lower Quartile Rent, Log Std Dev ...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  Time Frame          Location Id Dwelling Type Number Of Beds Total Bonds
1 Apr  1 1993 12:00AM -99         ALL           1               2910
2 Apr  1 1993 12:00AM -99         ALL           2               8370
3 Apr  1 1993 12:00AM -99         ALL           3               8406
4 Apr  1 1993 12:00AM -99         ALL           4               1563
5 Apr  1 1993 12:00AM -99         ALL           5+               315
6 Apr  1 1993 12:00AM -99         ALL           ALL            22002
  Active Bonds Closed Bonds Median Rent Geometric Mean Rent Upper Quartile Rent
1  12456        2694        110         109                 130
2  37881        7113        140         140                 165
3  38136        6876        170         168                 200
4   7875        1251        200         200                 260
5   2103         255        240         217                 300
6 100128       18495        150         150                 185
  Lower Quartile Rent Log Std Dev Weekly Rent
1  90                 0.34
2 120                 0.29
3 140                 0.35
4 160                 0.43
5 160                 0.62
6 120                 0.38

In [39]:
problems(d2)
spec(d2)

    row     col expected actual
1   224222  10  a double 1,156
2   230622  10  a double 1,156
3   232848  10  a double 1,000
4   232858  10  a double 1,100
5   239540  10  a double 1,063
6   477876  10  a double 1,038
7   481930  10  a double 1,038
8   484389  10  a double 1,038
9   484523  10  a double 1,038
10  484600  10  a double 1,038
11  484659  10  a double 1,038
12  486922  10  a double 1,038
13  487035  10  a double 1,038
14  487092  10  a double 1,038
15  487430  10  a double 1,000
16  491430  10  a double 1,000
17  493866  10  a double 1,000
18  493892  10  a double 1,000
19  493918  10  a double 1,000
20  493963  10  a double 1,000
21  494019  10  a double 1,000
22  496234  10  a double 1,000
23  496346  10  a double 1,000
24  496401  10  a double 1,000
25  496733  10  a double 1,125
26  498404  10  a double 1,125
27  500719  10  a double 1,125
28  503125  10  a double 1,125
29  503154  10  a double 1,125
30  503181  10  a double 1,125
⋮   ⋮       ⋮   ⋮        ⋮
282 1005951 10  a double 1,050
283 1005960 10  a double 1,025
284 1006511 10  a double 1,050
285 1006517 10  a double 1,025
286 1006537 10  a double 1,050
287 1006542 10  a double 1,025
288 1006556 10  a double 1,050
289 1006561 10  a double 1,025
290 1006572 10  a double 1,050
291 1006575 10  a double 1,025
292 1006599 10  a double 1,050
293 1006609 10  a double 1,025
294 1006618 10  a double 1,050
295 1006620 10  a double 1,025
296 1006638 10  a double 1,050
297 1006645 10  a double 1,025
298 1006660 10  a double 1,050
299 1006668 10  a double 1,025
300 1006708 10  a double 1,050
301 1006717 10  a double 1,025
302 1006765 10  a double 1,050
303 1006774 10  a double 1,025
304 1007206 10  a double 1,050
305 1007211 10  a double 1,025
306 1007574 10  a double 1,050
307 1007580 10  a double 1,213
308 1007626 10  a double 1,050
309 1007632 10  a double 1,050
310 1007638 10  a double 1,025
311 1007653 10  a double 1,050
    file
1   /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
2   /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
3   /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
4   /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
5   /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
6   /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
7   /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
8   /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
9   /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
10  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
11  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
12  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
13  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
14  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
15  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
16  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
17  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
18  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
19  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
20  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
21  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
22  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
23  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
24  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
25  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
26  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
27  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
28  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
29  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
30  /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
⋮   ⋮
282 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
283 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
284 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
285 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
286 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
287 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
288 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
289 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
290 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
291 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
292 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
293 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
294 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
295 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
296 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
297 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
298 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
299 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
300 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
301 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
302 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
303 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
304 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
305 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
306 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
307 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
308 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
309 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
310 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv
311 /Volumes/GoogleDrive/My Drive/grad/s1/stats765/project/Detailed Quarterly Tenancy.csv

cols(
  `Time Frame` = col_character(),
  `Location Id` = col_number(),
  `Dwelling Type` = col_character(),
  `Number Of Beds` = col_character(),
  `Total Bonds` = col_number(),
  `Active Bonds` = col_number(),
  `Closed Bonds` = col_number(),
  `Median Rent` = col_double(),
  `Geometric Mean Rent` = col_number(),
  `Upper Quartile Rent` = col_double(),
  `Lower Quartile Rent` = col_double(),
  `Log Std Dev Weekly Rent` = col_double()
)

In [51]:
d2

        Time Frame          Location Id Dwelling Type  Number Of Beds
1       Apr  1 1993 12:00AM    -99      ALL            1
2       Apr  1 1993 12:00AM    -99      ALL            2
3       Apr  1 1993 12:00AM    -99      ALL            3
4       Apr  1 1993 12:00AM    -99      ALL            4
5       Apr  1 1993 12:00AM    -99      ALL            5+
6       Apr  1 1993 12:00AM    -99      ALL            ALL
7       Apr  1 1993 12:00AM    -99      ALL            NA
8       Apr  1 1993 12:00AM    -99      Flat           1
9       Apr  1 1993 12:00AM    -99      Flat           2
10      Apr  1 1993 12:00AM    -99      Flat           3
11      Apr  1 1993 12:00AM    -99      Flat           4
12      Apr  1 1993 12:00AM    -99      Flat           5+
13      Apr  1 1993 12:00AM    -99      Flat           ALL
14      Apr  1 1993 12:00AM    -99      Flat           NA
15      Apr  1 1993 12:00AM    -99      House          1
16      Apr  1 1993 12:00AM    -99      House          2
17      Apr  1 1993 12:00AM    -99      House          3
18      Apr  1 1993 12:00AM    -99      House          4
19      Apr  1 1993 12:00AM    -99      House          5+
20      Apr  1 1993 12:00AM    -99      House          ALL
21      Apr  1 1993 12:00AM    -99      House          NA
22      Apr  1 1993 12:00AM    -99      Room           1
23      Apr  1 1993 12:00AM    -99      Room           ALL
24      Apr  1 1993 12:00AM 100700      ALL            2
25      Apr  1 1993 12:00AM 100700      ALL            3
26      Apr  1 1993 12:00AM 100700      ALL            ALL
27      Apr  1 1993 12:00AM 100700      Flat           2
28      Apr  1 1993 12:00AM 100700      Flat           ALL
29      Apr  1 1993 12:00AM 100700      House          3
30      Apr  1 1993 12:00AM 100700      House          ALL
⋮       ⋮                   ⋮           ⋮              ⋮
1007889 Oct  1 2021 12:00AM 363300      House          3
1007890 Oct  1 2021 12:00AM 363300      House          ALL
1007891 Oct  1 2021 12:00AM     NA      ALL            1
1007892 Oct  1 2021 12:00AM     NA      ALL            2
1007893 Oct  1 2021 12:00AM     NA      ALL            3
1007894 Oct  1 2021 12:00AM     NA      ALL            4
1007895 Oct  1 2021 12:00AM     NA      ALL            5+
1007896 Oct  1 2021 12:00AM     NA      ALL            ALL
1007897 Oct  1 2021 12:00AM     NA      ALL            NA
1007898 Oct  1 2021 12:00AM     NA      Apartment      1
1007899 Oct  1 2021 12:00AM     NA      Apartment      2
1007900 Oct  1 2021 12:00AM     NA      Apartment      3
1007901 Oct  1 2021 12:00AM     NA      Apartment      ALL
1007902 Oct  1 2021 12:00AM     NA      Apartment      NA
1007903 Oct  1 2021 12:00AM     NA      Boarding House 1
1007904 Oct  1 2021 12:00AM     NA      Boarding House ALL
1007905 Oct  1 2021 12:00AM     NA      Flat           1
1007906 Oct  1 2021 12:00AM     NA      Flat           2
1007907 Oct  1 2021 12:00AM     NA      Flat           3
1007908 Oct  1 2021 12:00AM     NA      Flat           ALL
1007909 Oct  1 2021 12:00AM     NA      House          1
1007910 Oct  1 2021 12:00AM     NA      House          2
1007911 Oct  1 2021 12:00AM     NA      House          3
1007912 Oct  1 2021 12:00AM     NA      House          4
1007913 Oct  1 2021 12:00AM     NA      House          5+
1007914 Oct  1 2021 12:00AM     NA      House          ALL
1007915 Oct  1 2021 12:00AM     NA      House          NA
1007916 Oct  1 2021 12:00AM     NA      Room           1
1007917 Oct  1 2021 12:00AM     NA      Room           ALL
1007918 Oct  1 2021 12:00AM     NA      Room           NA
        Total Bonds Active Bonds Closed Bonds Median Rent Geometric Mean Rent
1        2910        12456        2694        110         109
2        8370        37881        7113        140         140
3        8406        38136        6876        170         168
4        1563         7875        1251        200         200
5         315         2103         255        240         217
6       22002       100128       18495        150         150
7         438         1677         306        150         153
8        2718        11595        2538        110         109
9        6147        27126        5241        140         139
10        732         3660         690        175         177
11         96          612          84        200         181
12         33          444          33        245         178
13       9804        43752        8646        130         133
14         75          309          60        125         142
15        186          846         147        115         112
16       2220        10752        1872        145         144
17       7674        34476        6189        170         167
18       1467         7263        1167        200         201
19        282         1659         222        238         222
20      12192        56361        9840        165         166
21        363         1368         246        150         155
22          6            9           9         50          54
23          6            9           9         50          54
24          6           21           9        140          96
25          9           33           6        170         122
26         15           60          15        150         110
27          6           15           6        140          96
28          6           18           6        130          98
29          9           30           6        170         122
30          9           42           6        165         118
⋮       ⋮           ⋮            ⋮            ⋮           ⋮
1007889    6           48           3         570         330
1007890    9           78           9         560         309
1007891  498         2943         390          NA          NA
1007892  564         3903         324          NA          NA
1007893  537         4611         327          NA          NA
1007894  291         2169         165          NA          NA
1007895   69          522          48          NA          NA
1007896 2352        16788        1458          NA          NA
1007897  393         2637         207          NA          NA
1007898  207          960         165          NA          NA
1007899  126          750          93          NA          NA
1007900   27          162          24          NA          NA
1007901  387         2058         309          NA          NA
1007902   24          156          21          NA          NA
1007903   24          105          15          NA          NA
1007904   27          117          18          NA          NA
1007905   57          729          51          NA          NA
1007906   54          879          66          NA          NA
1007907    9          150          15          NA          NA
1007908  126         1929         141          NA          NA
1007909  132          624          75          NA          NA
1007910  381         2271         162          NA          NA
1007911  501         4299         288          NA          NA
1007912  285         2121         159          NA          NA
1007913   66          483          39          NA          NA
1007914 1722        12132         900          NA          NA
1007915  357         2334         174          NA          NA
1007916   81          525          87          NA          NA
1007917   87          549          90          NA          NA
1007918    6           21           3          NA          NA
        Upper Quartile Rent Lower Quartile Rent Log Std Dev Weekly Rent
1       130                  90                 0.34
2       165                 120                 0.29
3       200                 140                 0.35
4       260                 160                 0.43
5       300                 160                 0.62
6       185                 120                 0.38
7       200                 115                 0.43
8       130                  90                 0.33
9       160                 120                 0.29
10      220                 144                 0.34
11      250                 160                 0.50
12      289                 133                 0.82
13      160                 110                 0.34
14      170                 110                 0.43
15      140                  90                 0.39
16      170                 120                 0.30
17      200                 140                 0.36
18      260                 160                 0.43
19      300                 160                 0.59
20      200                 135                 0.38
21      200                 120                 0.43
22       50                  46                 0.90
23       50                  46                 0.90
24      165                 120                 0.09
25      200                 140                 0.16
26      185                 120                 0.18
27      160                 120                 0.09
28      160                 110                 0.10
29      200                 140                 0.16
30      200                 135                 0.18
⋮       ⋮                   ⋮                   ⋮
1007889 650                 495                 0.13
1007890 680                 470                 0.22
1007891  NA                  NA                   NA
1007892  NA                  NA                   NA
1007893  NA                  NA                   NA
1007894  NA                  NA                   NA
1007895  NA                  NA                   NA
1007896  NA                  NA                   NA
1007897  NA                  NA                   NA
1007898  NA                  NA                   NA
1007899  NA                  NA                   NA
1007900  NA                  NA                   NA
1007901  NA                  NA                   NA
1007902  NA                  NA                   NA
1007903  NA                  NA                   NA
1007904  NA                  NA                   NA
1007905  NA                  NA                   NA
1007906  NA                  NA                   NA
1007907  NA                  NA                   NA
1007908  NA                  NA                   NA
1007909  NA                  NA                   NA
1007910  NA                  NA                   NA
1007911  NA                  NA                   NA
1007912  NA                  NA                   NA
1007913  NA                  NA                   NA
1007914  NA                  NA                   NA
1007915  NA                  NA                   NA
1007916  NA                  NA                   NA
1007917  NA                  NA                   NA
1007918  NA                  NA                   NA

In [60]:
d2dtypes <- d2 %>% filter(`Dwelling Type` == 'Flat')

d2dtypes[order(d2dtypes$`Total Bonds`),]

       Time Frame          Location Id Dwelling Type Number Of Beds Total Bonds
1      Apr  1 1993 12:00AM 100700      Flat          2              6
2      Apr  1 1993 12:00AM 100700      Flat          ALL            6
3      Apr  1 1993 12:00AM 100800      Flat          2              6
4      Apr  1 1993 12:00AM 100800      Flat          ALL            6
5      Apr  1 1993 12:00AM 106100      Flat          ALL            6
6      Apr  1 1993 12:00AM 106900      Flat          ALL            6
7      Apr  1 1993 12:00AM 107100      Flat          2              6
8      Apr  1 1993 12:00AM 107200      Flat          ALL            6
9      Apr  1 1993 12:00AM 107500      Flat          1              6
10     Apr  1 1993 12:00AM 108300      Flat          ALL            6
11     Apr  1 1993 12:00AM 113000      Flat          ALL            6
12     Apr  1 1993 12:00AM 117200      Flat          ALL            6
13     Apr  1 1993 12:00AM 118300      Flat          2              6
14     Apr  1 1993 12:00AM 118700      Flat          ALL            6
15     Apr  1 1993 12:00AM 120000      Flat          2              6
16     Apr  1 1993 12:00AM 121800      Flat          2              6
17     Apr  1 1993 12:00AM 121900      Flat          2              6
18     Apr  1 1993 12:00AM 122700      Flat          2              6
19     Apr  1 1993 12:00AM 122800      Flat          2              6
20     Apr  1 1993 12:00AM 123200      Flat          ALL            6
21     Apr  1 1993 12:00AM 123300      Flat          2              6
22     Apr  1 1993 12:00AM 123300      Flat          ALL            6
23     Apr  1 1993 12:00AM 123400      Flat          2              6
24     Apr  1 1993 12:00AM 123400      Flat          ALL            6
25     Apr  1 1993 12:00AM 123600      Flat          2              6
26     Apr  1 1993 12:00AM 123900      Flat          ALL            6
27     Apr  1 1993 12:00AM 124400      Flat          2              6
28     Apr  1 1993 12:00AM 124400      Flat          ALL            6
29     Apr  1 1993 12:00AM 124600      Flat          ALL            6
30     Apr  1 1993 12:00AM 125200      Flat          ALL            6
⋮      ⋮                   ⋮           ⋮             ⋮              ⋮
138548 Apr  1 2003 12:00AM -99         Flat          ALL            12981
138549 Jan  1 2007 12:00AM -99         Flat          ALL            13257
138550 Oct  1 1998 12:00AM -99         Flat          ALL            13287
138551 Jul  1 1997 12:00AM -99         Flat          ALL            13332
138552 Apr  1 1998 12:00AM -99         Flat          ALL            13335
138553 Oct  1 2002 12:00AM -99         Flat          ALL            13461
138554 Jan  1 2006 12:00AM -99         Flat          ALL            13596
138555 Oct  1 2000 12:00AM -99         Flat          ALL            13716
138556 Jan  1 2005 12:00AM -99         Flat          ALL            13773
138557 Jul  1 2003 12:00AM -99         Flat          ALL            13785
138558 Oct  1 1999 12:00AM -99         Flat          ALL            14028
138559 Jan  1 1996 12:00AM -99         Flat          ALL            14214
138560 Apr  1 1999 12:00AM -99         Flat          ALL            14241
138561 Jul  1 2002 12:00AM -99         Flat          ALL            14274
138562 Apr  1 2000 12:00AM -99         Flat          ALL            14283
138563 Jul  1 1998 12:00AM -99         Flat          ALL            14313
138564 Oct  1 2001 12:00AM -99         Flat          ALL            14397
138565 Apr  1 2002 12:00AM -99         Flat          ALL            14436
138566 Apr  1 2001 12:00AM -99         Flat          ALL            14664
138567 Jul  1 1999 12:00AM -99         Flat          ALL            14709
138568 Jan  1 2004 12:00AM -99         Flat          ALL            14724
138569 Jan  1 1997 12:00AM -99         Flat          ALL            15000
138570 Jul  1 2000 12:00AM -99         Flat          ALL            15210
138571 Jul  1 2001 12:00AM -99         Flat          ALL            15441
138572 Jan  1 1998 12:00AM -99         Flat          ALL            16077
138573 Jan  1 2003 12:00AM -99         Flat          ALL            16191
138574 Jan  1 1999 12:00AM -99         Flat          ALL            17430
138575 Jan  1 2000 12:00AM -99         Flat          ALL            17880
138576 Jan  1 2001 12:00AM -99         Flat          ALL            18897
138577 Jan  1 2002 12:00AM -99         Flat          ALL            18921
       Active Bonds Closed Bonds Median Rent Geometric Mean Rent
1      15           6            140          96
2      18           6            130          98
3      15           3            140         123
4      15           3            130         123
5      30           6            130          94
6      45           6            130          96
7      18           6            140         108
8      18           3            130         103
9      15           3            110          95
10      9           6            130         103
11     45           9            130         118
12     18           3            130         181
13     54           3            140         162
14     15           6            130         219
15     21           0            140         167
16     24           3            140         153
17     51           9            140         163
18     33           3            140         174
19     18           6            140         147
20     12           3            130         133
21     21           3            140         170
22     30           3            130         159
23     12           3            140         188
24     24           3            130         178
25     39           6            140         170
26     12           3            130         148
27     24           3            140         152
28     24           3            130         159
29     24           3            130         158
30     33           3            130         169
⋮      ⋮            ⋮            ⋮           ⋮
138548 77037        12867        190         193
138549 74955        12237        230         230
138550 62781        14475        165         168
138551 60849        12522        170         170
138552 63444        12582        170         171
138553 75297        15405        180         184
138554 75726        12111        220         216
138555 68961        14973        170         171
138556 74991        12624        210         211
138557 77211        13611        190         191
138558 66168        14895        170         170
138559 55092        11871        150         159
138560 66336        13323        165         169
138561 77241        14991        180         184
138562 69123        13731        170         171
138563 63966        13791        170         170
138564 73737        15189        175         179
138565 77958        13857        180         186
138566 73314        13449        170         174
138567 67038        14010        165         169
138568 76266        13554        200         200
138569 59259        12432        165         168
138570 70218        14115        170         172
138571 74529        14226        170         176
138572 62694        13728        170         171
138573 76923        14568        185         190
138574 65421        14790        165         169
138575 68571        15480        165         171
138576 72099        15756        170         174
138577 77379        15282        175         180
       Upper Quartile Rent Lower Quartile Rent Log Std Dev Weekly Rent
1      160                 120                 0.09
2      160                 110                 0.10
3      160                 120                 0.13
4      160                 110                 0.13
5      160                 110                 0.12
6      160                 110                 0.13
7      160                 120                 0.09
8      160                 110                 0.20
9      130                  90                 0.09
10     160                 110                 0.20
11     160                 110                 0.41
12     160                 110                 0.18
13     160                 120                 0.17
14     160                 110                 0.34
15     160                 120                 0.57
16     160                 120                 0.12
17     160                 120                 0.12
18     160                 120                 0.07
19     160                 120                 0.24
20     160                 110                 0.28
21     160                 120                 0.06
22     160                 110                 0.36
23     160                 120                 0.22
24     160                 110                 0.24
25     160                 120                 0.09
26     160                 110                 0.12
27     160                 120                 0.18
28     160                 110                 0.19
29     160                 110                 0.35
30     160                 110                 0.21
⋮      ⋮                   ⋮                   ⋮
138548 260                 145                 0.43
138549 290                 180                 0.39
138550 215                 130                 0.40
138551 220                 130                 0.42
138552 220                 130                 0.41
138553 250                 140                 0.42
138554 280                 170                 0.41
138555 220                 130                 0.41
138556 270                 160                 0.41
138557 250                 145                 0.42
138558 220                 130                 0.41
138559 210                 120                 0.44
138560 220                 130                 0.40
138561 250                 140                 0.44
138562 220                 130                 0.41
138563 220                 130                 0.41
138564 230                 135                 0.43
138565 250                 140                 0.45
138566 225                 130                 0.42
138567 220                 130                 0.41
138568 265                 150                 0.42
138569 230                 130                 0.45
138570 220                 130                 0.41
138571 230                 135                 0.43
138572 228                 130                 0.43
138573 260                 140                 0.46
138574 220                 130                 0.42
138575 220                 130                 0.43
138576 230                 130                 0.44
138577 245                 130                 0.46